[#--
<div class="num">
	<a href="#" class="pageup">上一页</a>
	<a href="#">1</a>
	<a href="#">2</a>
	<a href="#" class="queren">3</a>
	<a href="#">4</a>
	<a href="#">5</a>
	<a href="#">6</a>
	<a href="#">7</a>···
	<a href="#">99</a>
	<a href="#" class="pagedown">下一页</a>
</div>
--]
[#assign steps=3]
[#assign leftoffset = steps]
[#assign midoffset1 = lp.pageNo-(steps-1)]
[#assign midoffset2 = lp.pageNo+(steps-1)]
[#assign rightoffset = lp.totalPage-(steps-1)]
[#if leftoffset gt lp.totalPage]
        [#assign leftoffset = lp.totalPage] 
[/#if]
[#if rightoffset lt 1]
        [#assign rightoffset = 1]
[#elseif leftoffset lt lp.totalPage && rightoffset lt leftoffset+1]
	[#assign rightoffset = leftoffset+1] 
[/#if]
[#if midoffset1 lt 1]
	[#assign midoffset1 = 1] 
[/#if]
[#if midoffset2 gt rightoffset-1 && rightoffset gt 1]
        [#assign midoffset2 = rightoffset-1] 
[#elseif midoffset2 gt lp.totalPage]
	[#assign midoffset2 = lp.totalPage]
[/#if]
[#if midoffset2 lt midoffset1]
		[#assign midoffset2 = midoffset1]
[/#if]
<div class="marg-30-t marg-30-b clearfix">[#t/]
	<ul class="pagination pull-right">[#t/]
[#--<span class='AtStart'>(共${lp.totalCount} 条)</span>--][#t/]
[#if lp.firstPage]<li><a href="javascript:;">首页</a></li><li><a href="javascript:;">&laquo;</a></li>[#t/]
[#else]<li><a href="javascript:;" onclick='${ajaxFunc}(1)'>首页</a></li><li><a href="javascript:;" onclick='${ajaxFunc}(${lp.prePage})'>&laquo;</a></li>[#t/]
[/#if]
[#-- 左侧列表 --]
[#list 1..leftoffset as i]
[#if lp.pageNo==i]<li><a href='javascript:;'>${i}</a></li>[#t/]
[#else]<li><a href='javascript:;' onclick='${ajaxFunc}(${i})'>${i}</a></li>[#t/]
[/#if]
[/#list]
[#-- 中间列表 --]
[#if (lp.pageNo gt leftoffset || lp.pageNo lt rightoffset) && rightoffset gt leftoffset+1]
[#-- 当前页左列表 --]
[#if midoffset1 gt leftoffset+1]...[#t/]
[/#if]
[#list midoffset1..midoffset2 as i]
[#if i lte leftoffset || i gte rightoffset]
[#elseif lp.pageNo==i]<li><a href='javascript:;'>${i}</a></li>[#t/]
[#else]<li><a href='javascript:;' onclick='${ajaxFunc}(${i})'>${i}</a></li>[#t/]
[/#if]
[/#list]
[#if midoffset2 lt rightoffset-1]...[#t/]
[/#if]
[/#if]
[#if leftoffset lt lp.totalPage && midoffset2 lt lp.totalPage]
[#list rightoffset..lp.totalPage as i]
[#if lp.pageNo==i]<li><a href='javascript:;'>${i}</a></li>[#t/]
[#else]<li><a href='javascript:;' onclick='${ajaxFunc}(${i})'>${i}</a></li>[#t/]
[/#if]
[/#list]
[/#if]
[#if lp.lastPage]<li><a href="javascript:;">&raquo;</a></li><li><a href="javascript:;">尾页</a></li>[#t/]
[#else]<li><a href='javascript:;' onclick='${ajaxFunc}(${lp.nextPage})'>&raquo;</a></li><li><a href="javascript:;" onclick='${ajaxFunc}(${lp.totalPage})'>尾页</a></li>[#t/]
[/#if]
	</ul>[#t/]
</div>[#t/]